/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.page;

import ui.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Role;
import model.UserDirectory;
import ui.page.F1_S3_ManageBranches;

/**
 *
 * @author archil
 */
public class F1_S2_AdminNavgtn extends javax.swing.JPanel {

    private JPanel mainWorkArea;
    private UserDirectory userDirectory;

    public F1_S2_AdminNavgtn(JPanel mainWorkArea, UserDirectory userDirectory) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.userDirectory = userDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnMngUsrAccnt = new javax.swing.JButton();
        btnMngBranch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Administrator Workspace");

        btnMngUsrAccnt.setText("Manage User Accounts >>");
        btnMngUsrAccnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngUsrAccntActionPerformed(evt);
            }
        });

        btnMngBranch.setText("Mamage Branches >>");
        btnMngBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngBranchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnMngBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMngUsrAccnt, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTitle)
                .addGap(55, 55, 55)
                .addComponent(btnMngUsrAccnt)
                .addGap(18, 18, 18)
                .addComponent(btnMngBranch)
                .addContainerGap(386, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngUsrAccntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngUsrAccntActionPerformed
        F1_S3_ManageUsers manageUsersPanel = new F1_S3_ManageUsers(mainWorkArea, userDirectory);
    mainWorkArea.add("ManageUsersPanel", (java.awt.Component)manageUsersPanel);
    CardLayout layout = (CardLayout) mainWorkArea.getLayout();
    layout.show(mainWorkArea, "ManageUsersPanel");
    }//GEN-LAST:event_btnMngUsrAccntActionPerformed

    private void btnMngBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngBranchActionPerformed
        F1_S3_ManageBranches manageBranchesPanel = new F1_S3_ManageBranches(mainWorkArea);
        mainWorkArea.add("ManageBranchesPanel", manageBranchesPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "ManageBranchesPanel");
    }//GEN-LAST:event_btnMngBranchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngBranch;
    private javax.swing.JButton btnMngUsrAccnt;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
