/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.page;

import ui.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.APP;
import model.Branch;
import model.RentalRequest;
import model.User;

;

/**
 *
 * @author archil
 */
public class F2_S2_BranchNavgtn extends javax.swing.JPanel {

    private JPanel mainWorkArea;
    private User branchManager;
    private Branch branch;
    
    public F2_S2_BranchNavgtn(JPanel mainWorkArea, User branchManager) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.branchManager = branchManager;
        
        // Find the branch managed by this branch manager
        APP app = APP.getInstance();
        for (Branch b : app.getBranches()) {
            if (b.getManagerName().equals(branchManager.getUsername())) {
                this.branch = b;
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnManageBooks = new javax.swing.JButton();
        btnManageAuthors = new javax.swing.JButton();
        btnManageRentalRequests = new javax.swing.JButton();
        btnViewRevenue = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Branch Manager Workspace");

        btnManageBooks.setText("Manage Books >>");
        btnManageBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBooksActionPerformed(evt);
            }
        });

        btnManageAuthors.setText("Mamage Authors >>");
        btnManageAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAuthorsActionPerformed(evt);
            }
        });

        btnManageRentalRequests.setText("Manage Rental Requesls >>");
        btnManageRentalRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRentalRequestsActionPerformed(evt);
            }
        });

        btnViewRevenue.setText("View Revenue >>");
        btnViewRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRevenueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnManageRentalRequests, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageAuthors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnViewRevenue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitle))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTitle)
                .addGap(55, 55, 55)
                .addComponent(btnManageBooks)
                .addGap(18, 18, 18)
                .addComponent(btnManageAuthors)
                .addGap(18, 18, 18)
                .addComponent(btnManageRentalRequests)
                .addGap(18, 18, 18)
                .addComponent(btnViewRevenue)
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBooksActionPerformed
        F2_S3_ManageBooks manageBooksPanel = new F2_S3_ManageBooks(mainWorkArea, branchManager);
        mainWorkArea.add("ManageBooksPanel", manageBooksPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "ManageBooksPanel");
    }//GEN-LAST:event_btnManageBooksActionPerformed

    private void btnManageAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAuthorsActionPerformed

        F2_S3_ManageAuthors manageAuthorsPanel = new F2_S3_ManageAuthors(mainWorkArea, branchManager);
        mainWorkArea.add("ManageAuthorsPanel", manageAuthorsPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "ManageAuthorsPanel");
    }//GEN-LAST:event_btnManageAuthorsActionPerformed

    private void btnManageRentalRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRentalRequestsActionPerformed

        F2_S3_Mng_Rntl_Req manageRentalRequestsPanel = new F2_S3_Mng_Rntl_Req(mainWorkArea, branchManager);
        mainWorkArea.add("ManageRentalRequestsPanel", manageRentalRequestsPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "ManageRentalRequestsPanel");
    }//GEN-LAST:event_btnManageRentalRequestsActionPerformed

    private void btnViewRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRevenueActionPerformed
        // TODO add your handling code here:
        if (branch == null) {
            JOptionPane.showMessageDialog(this, 
                "No branch information found for this manager.", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Calculate total revenue from approved and returned rental requests
        double totalRevenue = branch.getTotalRevenue();
        
        // Create a message with revenue details
        StringBuilder revenueDetails = new StringBuilder();
        revenueDetails.append("Branch: ").append(branch.getName()).append("\n\n");
        revenueDetails.append("Total Revenue: $").append(String.format("%.2f", totalRevenue)).append("\n\n");
        
        // Add a breakdown of revenue by status
        double approvedRevenue = 0;
        double returnedRevenue = 0;
        int approvedCount = 0;
        int returnedCount = 0;
        
        for (RentalRequest request : branch.getRentalRequests()) {
            if (request.getStatus().equals("APPROVED")) {
                approvedRevenue += request.getPrice();
                approvedCount++;
            } else if (request.getStatus().equals("RETURNED")) {
                returnedRevenue += request.getPrice();
                returnedCount++;
            }
        }
        
        revenueDetails.append("Revenue Breakdown:\n");
        revenueDetails.append("- From ").append(approvedCount).append(" approved rentals: $")
                    .append(String.format("%.2f", approvedRevenue)).append("\n");
        revenueDetails.append("- From ").append(returnedCount).append(" returned rentals: $")
                    .append(String.format("%.2f", returnedRevenue)).append("\n");
        
        // Show the revenue details
        JOptionPane.showMessageDialog(this, revenueDetails.toString(), "Revenue Report", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewRevenueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAuthors;
    private javax.swing.JButton btnManageBooks;
    private javax.swing.JButton btnManageRentalRequests;
    private javax.swing.JButton btnViewRevenue;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
