/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.page;

import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.APP;
import model.Author;
import model.AuthorDirectory;
import model.Book;
import model.Library;
import model.User;

/**
 *
 * @author archil
 */
public class F2_S4_Add_Book extends javax.swing.JPanel {
    private JPanel mainWorkArea;
    private Library library;
    private AuthorDirectory authorDirectory;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
    
    /**
     * Creates new form LoginScreen
     */
    public F2_S4_Add_Book(JPanel mainWorkArea, Library library) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.library = library;
        
        // Get the author directory from the APP singleton
        APP app = APP.getInstance();
        this.authorDirectory = app.getAuthorDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblBranchName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblBranchSupplier = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        txtAuthorName = new javax.swing.JTextField();
        lblBranchID = new javax.swing.JLabel();
        txtRegisteredDate = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        lblBranchSupplier1 = new javax.swing.JLabel();
        lblBranchSupplier2 = new javax.swing.JLabel();
        txtPages = new javax.swing.JTextField();
        txtLanguage = new javax.swing.JTextField();
        lblBranchSupplier3 = new javax.swing.JLabel();
        cmbAvailability = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("New Book");

        lblBranchName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBranchName.setText("Author Name:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblBranchSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBranchSupplier.setText("Registered Date:");

        lblBranchID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBranchID.setText("Serial Number:");

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        lblBranchSupplier1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBranchSupplier1.setText("Availability:");

        lblBranchSupplier2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBranchSupplier2.setText("Pages:");

        lblBranchSupplier3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBranchSupplier3.setText("Language:");

        cmbAvailability.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "available", "unavailable" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBranchName)
                                    .addComponent(lblBranchID))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBranchSupplier)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addComponent(txtRegisteredDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBranchSupplier1)
                                .addGap(18, 18, 18)
                                .addComponent(cmbAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBranchSupplier2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPages, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblBranchSupplier3)
                                .addGap(18, 18, 18)
                                .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblBranchName, lblBranchSupplier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(38, 38, 38)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchName))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegisteredDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchSupplier))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBranchSupplier1)
                    .addComponent(cmbAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchSupplier2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBranchSupplier3))
                .addGap(26, 26, 26)
                .addComponent(btnSave)
                .addGap(183, 183, 183))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Get input values
    String serialNumber = txtSerialNumber.getText().trim();
    String authorName = txtAuthorName.getText().trim();
    String registeredDateStr = txtRegisteredDate.getText().trim();
    String availability = (String) cmbAvailability.getSelectedItem();
    String language = txtLanguage.getText().trim();
    String pagesStr = txtPages.getText().trim();
    
    // Validate inputs
    if (serialNumber.isEmpty() || authorName.isEmpty() || registeredDateStr.isEmpty() || 
        availability.isEmpty() || language.isEmpty() || pagesStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "All fields are required.", 
            "Missing Information", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Check if the serial number already exists
    if (library.findBookBySerialNumber(serialNumber) != null) {
        JOptionPane.showMessageDialog(this, 
            "Serial Number already exists. Please use a different number.", 
            "Duplicate Serial Number", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Parse the number of pages
    int numberOfPages;
    try {
        numberOfPages = Integer.parseInt(pagesStr);
        if (numberOfPages <= 0) {
            throw new NumberFormatException();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, 
            "Number of pages must be a positive integer.", 
            "Invalid Input", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Parse the registered date
    Date registeredDate;
    try {
        registeredDate = dateFormat.parse(registeredDateStr);
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, 
            "Date format should be MM/DD/YYYY.", 
            "Invalid Date", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Find or create the author
    Author author = null;
    for (Author existingAuthor : authorDirectory.getAuthors()) {
        if (existingAuthor.getName().equalsIgnoreCase(authorName)) {
            author = existingAuthor;
            break;
        }
    }
    
    if (author == null) {
        // Create a new author if not found
        String newAuthorId = "A" + (authorDirectory.getAuthors().size() + 1);
        author = new Author(newAuthorId, authorName, new Date(), "Not specified");
        authorDirectory.addAuthor(author);
    }
    
    // Create a new book (fixed: using the correct name parameter)
    boolean isAvailable = "available".equalsIgnoreCase(availability);
    Book newBook = new Book(serialNumber, serialNumber, registeredDate, numberOfPages, language, author);
    newBook.setIsAvailable(isAvailable);
    
    // Add the book to the library
    library.addBook(newBook);
    
    JOptionPane.showMessageDialog(this, "Book added successfully!");
    
    // Go back to the previous panel
    backButtonActionPerformed(evt);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Go back to the previous panel
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
    layout.show(mainWorkArea, "ManageBooksPanel");
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbAvailability;
    private javax.swing.JLabel lblBranchID;
    private javax.swing.JLabel lblBranchName;
    private javax.swing.JLabel lblBranchSupplier;
    private javax.swing.JLabel lblBranchSupplier1;
    private javax.swing.JLabel lblBranchSupplier2;
    private javax.swing.JLabel lblBranchSupplier3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAuthorName;
    private javax.swing.JTextField txtLanguage;
    private javax.swing.JTextField txtPages;
    private javax.swing.JTextField txtRegisteredDate;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
    
}
