/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.page;

import ui.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Customer;

;

/**
 *
 * @author archil
 */
public class F3_S2_CustNavgtn extends javax.swing.JPanel {

    private JPanel mainWorkArea;
    private Customer customer;

    public F3_S2_CustNavgtn(JPanel mainWorkArea, Customer customer) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.customer = customer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBrowseBookCatalog = new javax.swing.JButton();
        btnViewRentalHistory = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Customer Workspace");

        btnBrowseBookCatalog.setText("Browse Book Catalog>>");
        btnBrowseBookCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseBookCatalogActionPerformed(evt);
            }
        });

        btnViewRentalHistory.setText("View Rental History>>");
        btnViewRentalHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRentalHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnViewRentalHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBrowseBookCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTitle)
                .addGap(55, 55, 55)
                .addComponent(btnBrowseBookCatalog)
                .addGap(18, 18, 18)
                .addComponent(btnViewRentalHistory)
                .addContainerGap(386, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseBookCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseBookCatalogActionPerformed
        // Navigate to Browse Book Catalog panel
        F3_S3_BrowBookCatalog browseBookCatalogPanel = new F3_S3_BrowBookCatalog(mainWorkArea, customer);
        mainWorkArea.add("BrowseBookCatalogPanel", browseBookCatalogPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "BrowseBookCatalogPanel");
    }//GEN-LAST:event_btnBrowseBookCatalogActionPerformed

    private void btnViewRentalHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRentalHistoryActionPerformed
        // Navigate to View Rental History panel
        F3_S3_ViewRentalHistory viewRentalHistoryPanel = new F3_S3_ViewRentalHistory(mainWorkArea, customer);
        mainWorkArea.add("ViewRentalHistoryPanel", viewRentalHistoryPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "ViewRentalHistoryPanel");
    }//GEN-LAST:event_btnViewRentalHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseBookCatalog;
    private javax.swing.JButton btnViewRentalHistory;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
