/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.page;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.APP;
import model.Customer;
import model.CustomerDirectory;
import model.User;
import model.UserDirectory;

/**
 *
 * @author archil
 */
public class F3_S1_CustLoginScreen extends javax.swing.JPanel {

    private JPanel mainWorkArea;
    private UserDirectory userDirectory;
    private CustomerDirectory customerDirectory;
    
    
    /**
     * Creates new form LoginScreen
     */
    public F3_S1_CustLoginScreen(JPanel mainWorkArea, UserDirectory userDirectory, CustomerDirectory customerDirectory) {
    initComponents();
    this.mainWorkArea = mainWorkArea;
    this.userDirectory = userDirectory;
    this.customerDirectory = customerDirectory;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblSupplier = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Welcom to the library, Login to Customer Workspace");

        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRole.setText("User Name:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblSupplier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSupplier.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(lblTitle)
                .addContainerGap(111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRole)
                    .addComponent(lblSupplier))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(222, 222, 222))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRole, lblSupplier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSupplier)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(btnLogin)
                .addGap(278, 278, 278))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get input values
    String username = txtUserName.getText().trim();
    String password = txtPassword.getText().trim();
    
    // Validate inputs
    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Username and password are required.", 
            "Missing Information", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // 确保使用 APP 单例中的目录以获得正确的用户和客户数据
    APP app = APP.getInstance();
    UserDirectory globalUserDir = app.getUserDirectory();
    CustomerDirectory globalCustomerDir = app.getCustomerDirectory();
    
    // 使用全局用户目录查找用户
    User user = globalUserDir.findUserByUsername(username);
    
    // 检查用户是否存在且密码匹配
    if (user != null && user.getPassword().equals(password) && 
        user.getProfile().getRole().getRoleName().equals("Customer")) {
        
        // 从全局客户目录查找对应的客户
        Customer customer = globalCustomerDir.findCustomerByUsername(username);
        
        if (customer != null) {
            JOptionPane.showMessageDialog(this, "Login Successful!");
            
            // 导航到客户导航面板
            F3_S2_CustNavgtn custNavPanel = new F3_S2_CustNavgtn(mainWorkArea, customer);
            mainWorkArea.add("CustomerNavPanel", custNavPanel);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.show(mainWorkArea, "CustomerNavPanel");
        } else {
            JOptionPane.showMessageDialog(this, 
                "Customer profile not found. Please contact system administrator.", 
                "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, 
            "Invalid username or password, or you are not registered as a customer.", 
            "Login Failed", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

}
