/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.Branch;

import ui.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.Owner;
import model.OwnerDirectory;
import ui.service.Services;
import model.ServiceCatalog;
import ui.service.ManageVehicles;
import ui.service.ViewVehiclesDetails;
import ui.user.Vehicles_Owner;
;

/**
 *
 * @author archil
 */
public class S2_Navgtn extends javax.swing.JPanel {

    private JPanel mainWorkArea;
    private OwnerDirectory ownerDirectory;
    private ServiceCatalog serviceCatalog;
   

    public S2_Navgtn(JPanel mainWorkArea, OwnerDirectory ownerDirectory, ServiceCatalog serviceCatalog) {
        initComponents(); // 仅初始化 UI
        this.mainWorkArea = mainWorkArea;
        this.ownerDirectory = ownerDirectory;
        this.serviceCatalog = serviceCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnServices = new javax.swing.JButton();
        btnVehicle_Owner = new javax.swing.JButton();
        btnManageVehicles = new javax.swing.JButton();
        btnManageVehicles1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Branch Manager Workspace");

        btnServices.setText("Manage Books >>");
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });

        btnVehicle_Owner.setText("Mamage Authors >>");
        btnVehicle_Owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicle_OwnerActionPerformed(evt);
            }
        });

        btnManageVehicles.setText("Manage Rental Requesls >>");
        btnManageVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehiclesActionPerformed(evt);
            }
        });

        btnManageVehicles1.setText("View Revenue >>");
        btnManageVehicles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehicles1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnManageVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVehicle_Owner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnManageVehicles1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblTitle))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblTitle)
                .addGap(55, 55, 55)
                .addComponent(btnServices)
                .addGap(18, 18, 18)
                .addComponent(btnVehicle_Owner)
                .addGap(18, 18, 18)
                .addComponent(btnManageVehicles)
                .addGap(18, 18, 18)
                .addComponent(btnManageVehicles1)
                .addContainerGap(304, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        Services panel = new Services(mainWorkArea, ownerDirectory,serviceCatalog);
        mainWorkArea.add(panel, "Services");
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "Services");
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnVehicle_OwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicle_OwnerActionPerformed
        // TODO add your handling code here:
        Vehicles_Owner panel = new Vehicles_Owner(mainWorkArea, ownerDirectory, serviceCatalog);
        mainWorkArea.add(panel, "VehiclesOwner");
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "VehiclesOwner");
    }//GEN-LAST:event_btnVehicle_OwnerActionPerformed

    private void btnManageVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehiclesActionPerformed
        // TODO add your handling code here:
        ManageVehicles panel = new ManageVehicles(mainWorkArea, ownerDirectory, serviceCatalog);
        mainWorkArea.add(panel, "ManageVehicles");
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "ManageVehicles");
    }//GEN-LAST:event_btnManageVehiclesActionPerformed

    private void btnManageVehicles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehicles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageVehicles1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageVehicles;
    private javax.swing.JButton btnManageVehicles1;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnVehicle_Owner;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
