/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddSupplier.java
 *
 * Created on Oct 1, 2011, 11:55:16 AM
 */

package ui.user;

import model.Owner;
import model.OwnerDirectory;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.Service;
import model.ServiceCatalog;
import model.Vehicle;
import ui.MainJFrame;


/**
 *
 * @author Rushabh
 */
public class Vehicles_Owner extends javax.swing.JPanel {

    private OwnerDirectory ownerDirectory;
    private ServiceCatalog serviceCatalog;
    private JPanel workArea;
    
    /** Creates new form AddSupplier */
    public Vehicles_Owner(JPanel workArea, OwnerDirectory ownerDirectory, ServiceCatalog serviceCatalog) {
        initComponents();
        this.workArea = workArea;
        this.ownerDirectory = ownerDirectory;
        this.serviceCatalog = serviceCatalog;
        
        initializeServiceComboBox();
    }
    
    private void initializeServiceComboBox() {
    // 清空下拉框
    sevicCombo.removeAllItems();
    
    // 添加默认空项
    sevicCombo.addItem("  ");
    
    // 检查 serviceCatalog 是否为空
    if (serviceCatalog == null) {
        sevicCombo.addItem("No services available");
        return;
    }
    
    // 使用 HashSet 防止重复
    Set<String> uniqueServices = new HashSet<>();
    
    // 添加服务，确保不重复
    for (Service service : serviceCatalog.getServiceList()) {
        String serviceName = service.getServiceName();
        if (serviceName != null && !serviceName.trim().isEmpty() && 
            uniqueServices.add(serviceName)) {
            sevicCombo.addItem(serviceName);
        }
    }
    
    // 如果没有服务，添加默认提示
    if (sevicCombo.getItemCount() == 1) {
        sevicCombo.addItem("No services available");
    }
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtOID = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        lblFName = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtservDate = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        lblLName = new javax.swing.JLabel();
        lblServDate = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        txtVehiID = new javax.swing.JTextField();
        lblMake = new javax.swing.JLabel();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        lblReNum = new javax.swing.JLabel();
        txtReNum = new javax.swing.JTextField();
        sevicCombo = new javax.swing.JComboBox<>();
        lblservOpt = new javax.swing.JLabel();
        lblVehiID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblName.setText("Owner ID:");

        txtOID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOIDActionPerformed(evt);
            }
        });

        lblTitle.setText("Owner Details");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        lblFName.setText("NameOwner First Name");

        txtFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNameActionPerformed(evt);
            }
        });

        txtservDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtservDateActionPerformed(evt);
            }
        });

        txtLName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLNameActionPerformed(evt);
            }
        });

        lblLName.setText("Owner Last Name:");

        lblServDate.setText("Service Date:");

        lblTitle1.setText("Vehicle Details");

        txtVehiID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehiIDActionPerformed(evt);
            }
        });

        lblMake.setText("Make:");

        txtMake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMakeActionPerformed(evt);
            }
        });

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        lblModel.setText("Model:");

        lblReNum.setText("Registration Number:");

        txtReNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReNumActionPerformed(evt);
            }
        });

        sevicCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Oil Change", "Car Wash", "Puncture" }));
        sevicCombo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                sevicComboComponentShown(evt);
            }
        });
        sevicCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevicComboActionPerformed(evt);
            }
        });

        lblservOpt.setText("Service Opted:");

        lblVehiID.setText("Vehicle ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblVehiID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTitle1)
                                        .addComponent(txtVehiID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblTitle)
                                        .addComponent(txtOID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtservDate, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblMake)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblModel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblReNum)
                                        .addComponent(lblservOpt))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtReNum, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                        .addComponent(sevicCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblServDate)
                                .addGap(432, 432, 432))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFName)
                            .addComponent(lblName)
                            .addComponent(lblLName))
                        .addGap(432, 432, 432)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtservDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServDate))
                .addGap(27, 27, 27)
                .addComponent(lblTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVehiID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehiID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblReNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sevicCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblservOpt))
                .addGap(45, 45, 45)
                .addComponent(btnAdd)
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        // 获取所有输入字段
    String ownerId = txtOID.getText().trim();
    String firstName = txtFName.getText().trim();
    String lastName = txtLName.getText().trim();
    String serviceDateText = txtservDate.getText().trim();
    String vehicleId = txtVehiID.getText().trim();
    String make = txtMake.getText().trim();
    String model = txtModel.getText().trim();
    String regNumber = txtReNum.getText().trim();
    String selectedService = (String) sevicCombo.getSelectedItem();
    
    // **验证 Service Date**
    LocalDate serviceDate = null;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd"); // 指定日期格式

    try {
        if (serviceDateText.isEmpty()) {
            serviceDate = LocalDate.now(); // 如果用户未输入，默认当前日期
        } else {
            serviceDate = LocalDate.parse(serviceDateText);
        }
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this,
            "Invalid date format. Please use YYYY-MM-DD",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // 验证 Service ID 是否已存在
    if (serviceCatalog.findServiceById(selectedService) != null) {
        JOptionPane.showMessageDialog(this,
            "Service ID already exists. Please enter a unique Service ID.",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return; // 阻止继续执行
    }

    // 验证 Vehicle ID 是否已存在
    for (Owner owner : ownerDirectory.getOwnerList()) {
        if (owner.getVehicleCatalog().findVehicle(vehicleId) != null) {
            JOptionPane.showMessageDialog(this,
                "Vehicle ID already exists. Please enter a unique Vehicle ID.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
            return; // 阻止继续执行
        }
    }

    try {
        // 创建并设置 Owner
        Owner owner = ownerDirectory.addOwner();
        owner.setOwnerID(Integer.parseInt(ownerId));
        owner.setOwnerFirstName(firstName);
        owner.setOwnerLastName(lastName);
        owner.setServiceDate(serviceDate);

        // 创建并设置 Vehicle
        Vehicle vehicle = new Vehicle();
        vehicle.setVehicleID(vehicleId);
        vehicle.setMake(make);
        vehicle.setModel(model);
        vehicle.setRegistrationNumber(regNumber);

        // 添加车辆到 Owner
        owner.getVehicleCatalog().addVehicle(vehicle);

        // 选择了服务，则添加
        if (selectedService != null && !selectedService.trim().isEmpty() && !"  ".equals(selectedService)) {
            Service service = serviceCatalog.findServiceByName(selectedService);
            if (service != null) {
                vehicle.addService(service);
                System.out.println("Service added to vehicle: " + service.getServiceName());
            } else {
                System.out.println("Service not found in ServiceCatalog: " + selectedService);
            }
        }

        JOptionPane.showMessageDialog(this,
            "Owner and vehicle successfully added",
            "Success",
            JOptionPane.INFORMATION_MESSAGE);
            
        clearFields(); // 清空输入字段
        backAction();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Invalid number format in ID field",
            "Error",
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainJFrame mainFrame = (MainJFrame) SwingUtilities.getWindowAncestor(this);
        String selectedService = mainFrame.getSelectedService(); //获取存储的服务
        if (!selectedService.isEmpty()) {
        System.out.println("User selected service: " + selectedService); //确保数据已存储
        } else {
            System.out.println("No service selected.");
        }
        backAction();
    }//GEN-LAST:event_backButtonActionPerformed

    private void sevicComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevicComboActionPerformed
        //TODO add your handling code here:
//    // 防止空指针异常
//    if (serviceCatalog == null) return;
//
//    // 获取当前已存在的服务名称
//    Set<String> existingServices = new HashSet<>();
//    for (int i = 0; i < sevicCombo.getItemCount(); i++) {
//        existingServices.add(sevicCombo.getItemAt(i));
//    }
//
//    // 清空旧数据
//    sevicCombo.removeAllItems();
//    sevicCombo.addItem("  "); // 默认空项
//
//    // 添加所有服务
//    for (Service service : serviceCatalog.getServiceList()) {
//        String serviceName = service.getServiceName();
//        if (serviceName != null && !serviceName.trim().isEmpty() && 
//            !existingServices.contains(serviceName)) {
//            sevicCombo.addItem(serviceName);
//            System.out.println("Adding service: " + serviceName);
//        }
//    }
//    
//    // 如果没有服务，添加默认提示
//    if (sevicCombo.getItemCount() == 1) {
//        sevicCombo.addItem("No services available");
//    }
    }//GEN-LAST:event_sevicComboActionPerformed

    private void sevicComboComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_sevicComboComponentShown
        // TODO add your handling code here:
        // 获取 MainJFrame 实例
    MainJFrame mainFrame = (MainJFrame) SwingUtilities.getWindowAncestor(this);
    
    // 获取之前存储的 selectedService
    String storedService = mainFrame.getSelectedService();
    
    // 重新初始化服务列表（确保只初始化一次）
    initializeServiceComboBox();
    
    // 如果之前有选择的服务，就在 JComboBox 里自动选中它
    if (storedService != null && !storedService.isEmpty()) {
        sevicCombo.setSelectedItem(storedService);
        System.out.println(storedService);
    }
    }//GEN-LAST:event_sevicComboComponentShown

    private void txtOIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOIDActionPerformed
        // TODO add your handling code here:
        System.out.println(txtOID.getText());
    }//GEN-LAST:event_txtOIDActionPerformed

    private void txtFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNameActionPerformed
        // TODO add your handling code here:
        System.out.println(txtFName.getText());
    }//GEN-LAST:event_txtFNameActionPerformed

    private void txtLNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLNameActionPerformed
        // TODO add your handling code here:
        System.out.println(txtLName.getText());
    }//GEN-LAST:event_txtLNameActionPerformed

    private void txtservDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtservDateActionPerformed
        // TODO add your handling code here:
        System.out.println(txtservDate.getText());
    }//GEN-LAST:event_txtservDateActionPerformed

    private void txtVehiIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehiIDActionPerformed
        // TODO add your handling code here:
        System.out.println(txtVehiID.getText());
    }//GEN-LAST:event_txtVehiIDActionPerformed

    private void txtMakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMakeActionPerformed
        // TODO add your handling code here:
        System.out.println(txtMake.getText());
    }//GEN-LAST:event_txtMakeActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
        System.out.println(txtModel.getText());
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtReNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReNumActionPerformed
        // TODO add your handling code here:
        System.out.println(txtReNum.getText());
    }//GEN-LAST:event_txtReNumActionPerformed

      
    private void backAction() {
        // 清理当前面板
        workArea.remove(this);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.previous(workArea);
    }
    
    private void clearFields() {
    txtOID.setText("");
    txtFName.setText("");
    txtLName.setText("");
    txtservDate.setText("");
    txtVehiID.setText("");
    txtMake.setText("");
    txtModel.setText("");
    txtReNum.setText("");
    sevicCombo.setSelectedIndex(0);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblMake;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblReNum;
    private javax.swing.JLabel lblServDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblVehiID;
    private javax.swing.JLabel lblservOpt;
    private javax.swing.JComboBox<String> sevicCombo;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOID;
    private javax.swing.JTextField txtReNum;
    private javax.swing.JTextField txtVehiID;
    private javax.swing.JTextField txtservDate;
    // End of variables declaration//GEN-END:variables


}
