/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import javax.swing.JOptionPane;
import model.Product;

/**
 *
 * @author tiankaining
 */
public class CreatePanel extends javax.swing.JPanel {
    Product product;

    /**
     * Creates new form CreatePanel
     */
    public CreatePanel(Product p) {
        initComponents();
        product = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtPActiv = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPActiv = new javax.swing.JLabel();
        txtDesti = new javax.swing.JTextField();
        lblDesti = new javax.swing.JLabel();
        txtStart = new javax.swing.JTextField();
        lblStart = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        lblEnd = new javax.swing.JLabel();
        lblBudget = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        txtNumTrav = new javax.swing.JTextField();
        lblNumTrav = new javax.swing.JLabel();
        lblMoTrans = new javax.swing.JLabel();
        txtMoTrans = new javax.swing.JTextField();
        txtAccom = new javax.swing.JTextField();
        lblAccom = new javax.swing.JLabel();
        txtECNum = new javax.swing.JTextField();
        lblECNum = new javax.swing.JLabel();
        lblNotes = new javax.swing.JLabel();
        txtNotes = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTPNum = new javax.swing.JLabel();
        txtTPNum = new javax.swing.JTextField();
        lblBRNum = new javax.swing.JLabel();
        txtBRNum = new javax.swing.JTextField();
        lblPFood = new javax.swing.JLabel();
        txtPFood = new javax.swing.JTextField();
        lblSLimit = new javax.swing.JLabel();
        txtSLimit = new javax.swing.JTextField();
        lblInsur = new javax.swing.JLabel();
        txtInsur = new javax.swing.JTextField();
        lblWLimit = new javax.swing.JLabel();
        txtWLimit = new javax.swing.JTextField();
        lblPClimat = new javax.swing.JLabel();
        txtPClimat = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        lblTitle.setText("Create Trip Profile");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblName.setText("Trip Name");

        lblPActiv.setText("Preferred Activities");

        lblDesti.setText("Destination");

        lblStart.setText("Start Date");

        lblEnd.setText("End Date");

        lblBudget.setText("Budget");

        lblNumTrav.setText("Number of Travelers");

        lblMoTrans.setText("Mode of Transportation");

        lblAccom.setText("Accommodation Type");

        lblECNum.setText("Emergency Contact Number");

        lblNotes.setText("Notes/Description");

        txtNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotesActionPerformed(evt);
            }
        });

        lblEmail.setText("Traveler Email");

        lblTPNum.setText("Traveler Phone Number");

        lblBRNum.setText("Booking Reference Number");

        lblPFood.setText("Food Preference");

        lblSLimit.setText("Luggage Size Limit");

        lblInsur.setText("Travel Insurance");

        lblWLimit.setText("Luggage Weight Limit");

        lblPClimat.setText("Climate Preference");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(txtECNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAccom)
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNotes)
                                            .addComponent(lblECNum)
                                            .addComponent(lblEmail)
                                            .addComponent(lblTPNum)
                                            .addComponent(lblBRNum)
                                            .addComponent(lblPFood)
                                            .addComponent(lblSLimit)
                                            .addComponent(lblInsur)
                                            .addComponent(lblWLimit)
                                            .addComponent(lblPClimat)
                                            .addComponent(lblPActiv))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPActiv)
                                    .addComponent(txtAccom, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPClimat, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInsur, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPFood, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBRNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTPNum, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMoTrans)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtMoTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNumTrav)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtNumTrav, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBudget)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEnd)
                                        .addGap(36, 36, 36)
                                        .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblDesti)
                                            .addComponent(lblStart)
                                            .addComponent(lblName)
                                            .addComponent(lblTitle))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDesti, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSave)
                                    .addComponent(lblTitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDesti)
                                    .addComponent(txtDesti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStart))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEnd)
                                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBudget)
                                    .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNumTrav)
                                    .addComponent(txtNumTrav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMoTrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMoTrans))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAccom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAccom))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPActiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblECNum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtECNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNotes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTPNum))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTPNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblBRNum))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBRNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPFood))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSLimit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWLimit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPClimat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPClimat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPActiv))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // 获取用户输入的数据
    String tripName = txtName.getText();
    String destination = txtDesti.getText();
    String startDate = txtStart.getText();
    String endDate = txtEnd.getText();
    String budget = txtBudget.getText();
    String numberOfTravelers = txtNumTrav.getText();
    String modeOfTransportation = txtMoTrans.getText();
    String accommodationType = txtAccom.getText();
    String emergencyContact = txtECNum.getText();
    String notes = txtNotes.getText();
    String travelerEmail = txtEmail.getText();
    String travelerPhoneNumber = txtTPNum.getText();
    String bookingReference = txtBRNum.getText();
    String foodPreference = txtPFood.getText();
    String luggageSizeLimit = txtSLimit.getText();
    String travelInsurance = txtInsur.getText();
    String luggageWeightLimit = txtWLimit.getText();
    String climatePreference = txtPClimat.getText();
    String preferredActivities = txtPActiv.getText();

    // 保存到 Product 对象
    product.setTripName(tripName);
    product.setDestination(destination);
    product.setStartDate(startDate);
    product.setEndDate(endDate);
    product.setBudget(budget);
    product.setNumberOfTravelers(numberOfTravelers);
    product.setModeOfTransportation(modeOfTransportation);
    product.setAccommodationType(accommodationType);
    product.setEmergencyContact(emergencyContact);
    product.setNotes(notes);
    product.setTravelerEmail(travelerEmail);
    product.setTravelerPhoneNumber(travelerPhoneNumber);
    product.setBookingReference(bookingReference);
    product.setFoodPreference(foodPreference);
    product.setLuggageSizeLimit(luggageSizeLimit);
    product.setTravelInsurance(travelInsurance);
    product.setLuggageWeightLimit(luggageWeightLimit);
    product.setClimatePreference(climatePreference);
    product.setPreferredActivities(preferredActivities);

    // 显示保存成功的消息
    JOptionPane.showMessageDialog(this, "Trip details saved successfully!", 
                                  "Success", JOptionPane.INFORMATION_MESSAGE);

    // 清空文本框
    txtName.setText("");
    txtDesti.setText("");
    txtStart.setText("");
    txtEnd.setText("");
    txtBudget.setText("");
    txtNumTrav.setText("");
    txtMoTrans.setText("");
    txtAccom.setText("");
    txtECNum.setText("");
    txtNotes.setText("");
    txtEmail.setText("");
    txtTPNum.setText("");
    txtBRNum.setText("");
    txtPFood.setText("");
    txtSLimit.setText("");
    txtInsur.setText("");
    txtWLimit.setText("");
    txtPClimat.setText("");
    txtPActiv.setText("");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAccom;
    private javax.swing.JLabel lblBRNum;
    private javax.swing.JLabel lblBudget;
    private javax.swing.JLabel lblDesti;
    private javax.swing.JLabel lblECNum;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblInsur;
    private javax.swing.JLabel lblMoTrans;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblNumTrav;
    private javax.swing.JLabel lblPActiv;
    private javax.swing.JLabel lblPClimat;
    private javax.swing.JLabel lblPFood;
    private javax.swing.JLabel lblSLimit;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTPNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWLimit;
    private javax.swing.JTextField txtAccom;
    private javax.swing.JTextField txtBRNum;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtDesti;
    private javax.swing.JTextField txtECNum;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtInsur;
    private javax.swing.JTextField txtMoTrans;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNotes;
    private javax.swing.JTextField txtNumTrav;
    private javax.swing.JTextField txtPActiv;
    private javax.swing.JTextField txtPClimat;
    private javax.swing.JTextField txtPFood;
    private javax.swing.JTextField txtSLimit;
    private javax.swing.JTextField txtStart;
    private javax.swing.JTextField txtTPNum;
    private javax.swing.JTextField txtWLimit;
    // End of variables declaration//GEN-END:variables
}
