/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Owner;
import model.OwnerDirectory;
import ui.admin.AdminWorkAreaJPanel;
import ui.supplier.SupplierWorkAreaJPanel;

/**
 *
 * @author archil
 */
public class LoginScreen extends javax.swing.JPanel {

    JPanel mainWorkArea;
    OwnerDirectory supplierDirectory;
    Owner selectedSupplier = null;
    
    
    /**
     * Creates new form LoginScreen
     */
    public LoginScreen(JPanel mainWorkArea, OwnerDirectory supplierDirectory) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.supplierDirectory = supplierDirectory;
        
        populateRoleCombo();
        populateSupplierCombo();
        updateSupplierVisibility();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnVehicle_Owner = new javax.swing.JButton();
        btnManageVehicles = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setText("Welcome to Vehicle Service Management Application");

        btnLogin.setText("Services");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnVehicle_Owner.setText("Vehicle & Owner");
        btnVehicle_Owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehicle_OwnerActionPerformed(evt);
            }
        });

        btnManageVehicles.setText("Manage Vehicles");
        btnManageVehicles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVehiclesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVehicle_Owner, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblTitle)
                .addGap(57, 57, 57)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnVehicle_Owner)
                .addGap(18, 18, 18)
                .addComponent(btnManageVehicles)
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        btnLogin.addActionListener(this::btnLoginActionPerformed);  
         String selectedRole = (String) cmbRoles.getSelectedItem();
        
        if ("Administrator".equals(selectedRole)) {
            AdminWorkAreaJPanel adminWork = new AdminWorkAreaJPanel(mainWorkArea, supplierDirectory);
            mainWorkArea.add("AdminWorkArea", adminWork);
            CardLayout layout = (CardLayout) mainWorkArea.getLayout();
            layout.next(mainWorkArea);
        } else {
            Owner supplier = (Owner) cmbSuppliers.getSelectedItem();
            if (supplier != null) {
                SupplierWorkAreaJPanel supplierWork = new SupplierWorkAreaJPanel(mainWorkArea, supplier);
                mainWorkArea.add("SupplierWorkArea", supplierWork);
                CardLayout layout = (CardLayout) mainWorkArea.getLayout();
                layout.next(mainWorkArea);
            } else {
                JOptionPane.showMessageDialog(this, "Please select a supplier");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnVehicle_OwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehicle_OwnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVehicle_OwnerActionPerformed

    private void btnManageVehiclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVehiclesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageVehiclesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnManageVehicles;
    private javax.swing.JButton btnVehicle_Owner;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
    
    public void populateRoleCombo() {
        cmbRoles.removeAllItems();
        cmbRoles.addItem("Administrator");
        cmbRoles.addItem("Supplier");
    }

    public void populateSupplierCombo() {
       cmbSuppliers.removeAllItems();
        for (Owner supplier : supplierDirectory.getSupplierList()) {
            cmbSuppliers.addItem(supplier);
        }
    }

    private void updateSupplierVisibility() {
         //To change body of generated methods, choose Tools | Templates.
         String selectedRole = (String) cmbRoles.getSelectedItem();
        boolean isSupplier = "Supplier".equals(selectedRole);
        cmbSuppliers.setVisible(isSupplier);
        if (isSupplier) {
            populateSupplierCombo();
        }
    }
}
