/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.time.LocalDate;
import model.Owner;
import model.OwnerDirectory;
import model.VehicleCatalog;
import model.Service;
import model.Vehicle;
import model.ServiceCatalog;

/**
 *
 * @author archil
 */
public class MainJFrame extends javax.swing.JFrame {
    private OwnerDirectory ownerDirectory;
    private Service service;
    private VehicleCatalog vehicleCatalog;
    private ServiceCatalog serviceCatalog;
    private String selectedService = "";
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents(); // NetBeans 生成的 UI 代码
        ownerDirectory = new OwnerDirectory(); // 初始化车主目录
        mainWorkArea = new javax.swing.JPanel();
        mainWorkArea.setLayout(new CardLayout());
        this.serviceCatalog = new ServiceCatalog();
        this.vehicleCatalog = new VehicleCatalog();
        
        // basic setings
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(800, 600);
        setResizable(false);
        getContentPane().add(mainWorkArea); // 加载导航界面

        populateDemoData(); // 预填充测试数据
        setNavigationPage(); // 设置导航页面
        
        //直接跳转到 NavigationPage
        NavigationPage navigationPage = new NavigationPage(mainWorkArea, ownerDirectory, serviceCatalog);
        mainWorkArea.add("NavigationPage", navigationPage);

        setContentPane(mainWorkArea); //让 `mainWorkArea` 成为默认面板
        ((CardLayout) mainWorkArea.getLayout()).show(mainWorkArea, "NavigationPage"); //显示 NavigationPage
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainWorkArea.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    private void setNavigationPage() {
        mainWorkArea.removeAll(); // 清空当前面板
        mainWorkArea.revalidate();
        mainWorkArea.repaint();
        
        NavigationPage navigationPage = new NavigationPage(mainWorkArea, ownerDirectory, serviceCatalog);
        navigationPage.setEnabled(true); // 确保页面可编辑
        mainWorkArea.add("NavigationPage", navigationPage);
        
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.show(mainWorkArea, "NavigationPage"); // 确保正确切换
    }
    
    // ✅ 提供 Getter 和 Setter 供其他面板访问
    public void setSelectedService(String service) {
        this.selectedService = service;
    }

    public String getSelectedService() {
        return selectedService;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainWorkArea;
    // End of variables declaration//GEN-END:variables

    private void populateDemoData() {

    // 创建 Owner（车主）
    Owner owner1 = new Owner(1, "John", "Doe", new VehicleCatalog(), LocalDate.of(2024, 2, 10));
    Owner owner2 = new Owner(2, "Alice", "Smith", new VehicleCatalog(), LocalDate.of(2024, 3, 15));
    Owner owner3 = new Owner(3, "Michael", "Johnson", new VehicleCatalog(), LocalDate.of(2024, 1, 20));
    Owner owner4 = new Owner(4, "Emily", "Davis", new VehicleCatalog(), LocalDate.of(2024, 4, 5));
    Owner owner5 = new Owner(5, "David", "Brown", new VehicleCatalog(), LocalDate.of(2024, 5, 12));

    // 添加 Owner 到目录
    ownerDirectory.addOwner(owner1);
    ownerDirectory.addOwner(owner2);
    ownerDirectory.addOwner(owner3);
    ownerDirectory.addOwner(owner4);
    ownerDirectory.addOwner(owner5);

    // 创建 Service（服务）
    Service service1 = new Service("101", "Oil Change", 50.0, "Mike","Sara", 30);
    Service service2 = new Service("102", "Car Wash", 20.0, "Sara","Mike", 15);
    Service service3 = new Service("103", "Puncture", 80.0, "Tom","Mike", 60);

    // 添加 Service 到 ServiceCatalog
    serviceCatalog.addService(service1);
    serviceCatalog.addService(service2);
    serviceCatalog.addService(service3);

    // 创建 Vehicle（车辆）并绑定到 Owner 和 Service
    Vehicle vehicle1 = new Vehicle("1", "Toyota", "Camry", 2020, "ABC123", owner1);
    Vehicle vehicle2 = new Vehicle("2", "Honda", "Civic", 2019, "XYZ789", owner2);
    Vehicle vehicle3 = new Vehicle("3", "Toyota", "Camry", 2021, "LMN456", owner3);
    Vehicle vehicle4 = new Vehicle("4", "Ford", "Mustang", 2018, "PQR678", owner4);
    Vehicle vehicle5 = new Vehicle("5", "BMW", "X5", 2022, "DEF345", owner5);

    // 显式添加服务到车辆
    vehicle1.addService(service1);
    vehicle1.addService(service2);
    vehicle2.addService(service2);
    vehicle3.addService(service3);
    vehicle4.addService(service1);
    vehicle5.addService(service2);

    // 添加 Vehicle 到 VehicleCatalog
    owner1.getVehicleCatalog().addVehicle(vehicle1);
    owner2.getVehicleCatalog().addVehicle(vehicle2);
    owner3.getVehicleCatalog().addVehicle(vehicle3);
    owner4.getVehicleCatalog().addVehicle(vehicle4);
    owner5.getVehicleCatalog().addVehicle(vehicle5);
    }   
}
