/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageSuppliers.java
 *
 * Created on Oct 1, 2011, 11:09:26 AM
 */

package ui.service;

import model.Owner;
import model.OwnerDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Service;
import model.Vehicle;
import model.VehicleCatalog;



/**
 *
 * @author Rushabh
 */
public class ManageVehicles extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private OwnerDirectory ownerDirectory;
    
    /** Creates new form ManageSuppliers */
    public ManageVehicles(JPanel upc, OwnerDirectory od) {
        initComponents();
        userProcessContainer = upc;
        ownerDirectory = od;
        refreshTable();
    }
    
    public void refreshTable() {
        
        DefaultTableModel model = (DefaultTableModel)tblVehicles.getModel();
        model.setRowCount(0);
        
        for(Owner s : ownerDirectory.getOwnerList()) {
            Object row[] = new Object[1];
            row[0] = s;
           // row[1] = s.getProductCatalog().getProductCount() == 0 ? "None" : s.getProductCatalog().getProductCount();
            model.addRow(row);
        }
    }
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        srlVehicles = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnviewdetail = new javax.swing.JButton();
        lblVehicleMang = new javax.swing.JLabel();
        TextSearchField = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        srlVehicles.setBackground(new java.awt.Color(255, 255, 255));

        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Owner lD", "Vehicle lD", "Service Opted", "Cost"
            }
        ));
        srlVehicles.setViewportView(tblVehicles);

        btnRemove.setText("Delete Account");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnviewdetail.setText("View Details");
        btnviewdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewdetailActionPerformed(evt);
            }
        });

        lblVehicleMang.setText("Manage Vehicles:");

        TextSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSearchFieldActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(srlVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnviewdetail)
                            .addGap(32, 32, 32)
                            .addComponent(btnRemove))
                        .addComponent(lblVehicleMang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(TextSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsearch))))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRemove, btnsearch, btnviewdetail});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVehicleMang, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(srlVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnviewdetail)
                    .addComponent(btnRemove))
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnviewdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewdetailActionPerformed
        // TODO add your handling code here:
        int row = tblVehicles.getSelectedRow();
        if(row < 0) {
            JOptionPane.showMessageDialog(null, "Please select a vehicle from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Owner owner = (Owner)tblVehicles.getValueAt(row, 0);
        ViewVehiclesDetails vd = new ViewVehiclesDetails(userProcessContainer, owner);
        userProcessContainer.add("ViewVehicleDetails", vd);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnviewdetailActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        String searchInput = TextSearchField.getText().trim();
    DefaultTableModel model = (DefaultTableModel) tblVehicles.getModel();
    model.setRowCount(0);  // 清空表格
    
    if (!searchInput.isEmpty()) {
        boolean found = false;
        
        for (Owner owner : ownerDirectory.getOwnerList()) {
            VehicleCatalog catalog = owner.getVehicleCatalog();
            ArrayList<Vehicle> results = catalog.searchVehicles(searchInput);
            
            if (!results.isEmpty()) {
                found = true;
                for (Vehicle vehicle : results) {
                    Object[] row = new Object[4];
                    row[0] = owner.getOwnerID();
                    row[1] = vehicle.getVehicleID();
                    if (!vehicle.getServicesOpted().isEmpty()) {
                        Service service = vehicle.getServicesOpted().get(0);
                        row[2] = service.getServiceType();
                        row[3] = service.getCost();
                    } else {
                        row[2] = "No Service";
                        row[3] = 0.0;
                    }
                    model.addRow(row);
                }
            }
        }
        
        if (!found) {
            JOptionPane.showMessageDialog(this, 
                "No matching records found.", 
                "Search Result", 
                JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
        }
    } else {
        refreshTable();
    }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int row = tblVehicles.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Owner s = (Owner)tblVehicles.getValueAt(row, 0);
        ownerDirectory.removeOwner(s);
        refreshTable();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void TextSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSearchFieldActionPerformed
        // TODO add your handling code here:
        String searchKey = TextSearchField.getText().trim();
        if (!searchKey.isEmpty()) {
            Owner result = ownerDirectory.searchOwner(searchKey);
            if (result != null) {
                System.out.println("Found Owner: " + result.getOwnerFirstName() + " " + result.getOwnerLastName());

            }
        } else {
        refreshTable(); // 确保你有一个方法来刷新界面数据
        }
    }//GEN-LAST:event_TextSearchFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextSearchField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnviewdetail;
    private javax.swing.JLabel lblVehicleMang;
    private javax.swing.JScrollPane srlVehicles;
    private javax.swing.JTable tblVehicles;
    // End of variables declaration//GEN-END:variables


}
